<?php

namespace MtzJaime\LocaleMiddleware\Console;

use Illuminate\Console\Command;

class RemoveTestFilesCommand extends Command
{

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'mtzJaime:remove-test-files';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Remove the test files generated by Locale Middleware Package';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $testView = resource_path('views/vendor/mtzJaime/index.blade.php');
        $testEN = resource_path('lang/en/languageTest.php');
        $testES = resource_path('lang/es/languageTest.php');
        $testDE = resource_path('lang/de/languageTest.php');

        file_exists($testView) === true ? unlink($testView) : $this->error('View not found');
        file_exists($testEN) === true ? unlink($testEN) : $this->error('EN translation not found');
        file_exists($testES) === true ? unlink($testES) : $this->error('ES translation not found');
        file_exists($testDE) === true ? unlink($testDE) : $this->error('DE translation not found');

        $this->info('Done!');
    }
}
